logging:
  receivers:
    my-app-receiver:
      type: files
      include_paths:
        - /var/log/webapp/csye6225.log 
      record_log_file_path: true

  processors:
    my-app-processor:
      type: parse_json
      time_key: timestamp 
      time_format: "%Y-%m-%dT%H:%M:%S"  
    move_severity:
      type: modify_fields
      fields:
        severity:
          move_from: jsonPayload.severity

  service:
    pipelines:
      default_pipeline:
        receivers: [my-app-receiver]
        processors: [my-app-processor, move_severity]
