account_file      = "account-gcp.json"
project_id        = "dev-gcp-414704"
source_image      = "centos-stream-8-v20240110"
ssh_username      = "packer"
image_description = "Custom image for webapp"
zone              = "us-east1-b"
region            = "us-east1"
image_name        = "webapp-packer-image"
