name: integration-test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: integration-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
      
    - name: Install dependencies
      run: npm install

    - name: Run the integration test
      run: npm test