name: integration-test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: integration-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run the integration test
      run: npm test